# numpy数组的基本计算  

🎈在这一部分，我们将介绍如何对数组进行一些基本的运算，我们将用反应时的例子来大致了解数组运算。

> 在心理学中，反应时是最常见的行为指标之一。在实验心理学中，我们知道根据不同的实验设计，反应时可以被划分为不同种类。比如：  

> * 在实验中，要求被试一看到红色就进行按键，这样得到的反应时被称为*简单反应时*，设为反应时A。  
> * 我们也可以增加刺激的种类，比如同时呈现红色与黄色，但要求被试只对红色作出反应，此时得到的反应时设为B反应时，包括*简单反应时和辨别反应时*。  

> * 现在，假设简单反应时服从平均值350，标准差25的正态分布；辨别反应时服从平均值为50，标准差为10的正态分布；  

我们可以分别生成简单反应时与辨别反应时：

In [1]:
import numpy as np

In [2]:
rt_A = np.random.normal(loc = 350,
                          scale = 25,
                          size = 50)

rt_check = np.random.normal(loc=50,
                            scale=10,
                            size=50)

我们知道，B反应时为简单反应时和辨别反应时之和，针对这个加法运算，我们既可以使用运算符 “+”，也可以使用函数np.add()

In [3]:
rt_B = rt_A + rt_check
print(rt_B)

[457.17143536 400.73211262 411.6734337  406.36986725 363.10418442
 389.19115651 409.39169019 395.4032963  405.41038701 436.87035467
 413.92232546 398.56293463 443.44703986 421.92084277 414.74748771
 430.33404349 412.9483014  377.33481426 400.52147701 428.1900987
 371.34717437 410.3149771  425.63702581 498.01765168 404.45854147
 424.72595662 373.46889397 399.27985622 421.89456312 400.2901821
 391.99089583 407.2586554  335.72922236 396.0566346  458.26281719
 416.74632126 419.10607526 380.69783027 428.64434555 425.47447982
 402.07720981 412.73425582 424.12119174 420.22727823 368.02345117
 406.14725556 374.18219147 436.70146272 427.81245049 384.0290556 ]


In [4]:
np.add(rt_A, rt_check)

array([457.17143536, 400.73211262, 411.6734337 , 406.36986725,
       363.10418442, 389.19115651, 409.39169019, 395.4032963 ,
       405.41038701, 436.87035467, 413.92232546, 398.56293463,
       443.44703986, 421.92084277, 414.74748771, 430.33404349,
       412.9483014 , 377.33481426, 400.52147701, 428.1900987 ,
       371.34717437, 410.3149771 , 425.63702581, 498.01765168,
       404.45854147, 424.72595662, 373.46889397, 399.27985622,
       421.89456312, 400.2901821 , 391.99089583, 407.2586554 ,
       335.72922236, 396.0566346 , 458.26281719, 416.74632126,
       419.10607526, 380.69783027, 428.64434555, 425.47447982,
       402.07720981, 412.73425582, 424.12119174, 420.22727823,
       368.02345117, 406.14725556, 374.18219147, 436.70146272,
       427.81245049, 384.0290556 ])

下表列出NumPy实现的运算符号及对应的函数：  

| 运算符	    | 对应的函数         | 说明                           |  
|---------------|---------------------|---------------------------------------|  
|``+``          |``np.add``           |加法 (例如 ``1 + 1 = 2``)         |  
|``-``          |``np.subtract``      |减法 (例如 ``3 - 2 = 1``)      |  
|``-``          |``np.negative``      |一元取负 (例如 ``-2``)          |  
|``*``          |``np.multiply``      |乘法 (例如 ``2 * 3 = 6``)   |  
|``/``          |``np.divide``        |除法 (例如 ``3 / 2 = 1.5``)       |  
|``//``         |``np.floor_divide``  |整除 (例如 ``3 // 2 = 1``)  |  
|``**``         |``np.power``         |求幂 (例如 ``2 ** 3 = 8``)  |  
|``%``          |``np.mod``           |模除 (例如 ``9 % 4 = 1``)|  


# 数组中的聚合函数  

除了了解数组的维度、长度，有时我们也需要了解数组中的平均值、最大值或最小值等等，我们仍然以简单反应时为例，简单了解数组中的聚合函数。

In [5]:
print(np.mean(rt_A))
print(np.min(rt_A))
print(np.max(rt_A))

357.8204871891329
292.8131334680511
422.0245432291557


## 多维聚合  

但如果数组是二维的，我们可能需要沿着行或列进行计算

In [6]:
rt_A = np.reshape(rt_A, (10, 5))
print(rt_A)

[[398.01922181 349.66691731 375.42376535 343.03393127 324.56682092]
 [350.88215111 360.49357502 345.71233977 355.93721642 373.63206921]
 [359.48944609 343.92821144 392.61146487 369.69518141 340.74278684]
 [388.43002901 371.12202719 327.2605937  345.17670971 365.12859998]
 [336.88768754 369.22203085 362.7178501  422.02454323 349.13732542]
 [360.36297457 327.71107039 352.75246451 364.45101093 358.52484166]
 [336.02543656 355.87945375 292.81313347 341.78208813 397.24041208]
 [379.39700871 357.29503412 325.50157435 376.97122392 373.45415883]
 [358.34835508 365.45294902 378.11608627 370.55627673 325.42969356]
 [356.19069125 335.74028677 379.87091476 365.83979831 334.37492616]]


此时我们需要指定一个*轴*让函数沿着这个方向进行聚合运算  

例如，我们可以计算每列的最小值，通过指定`axis=0`参数即可：

In [7]:
rt_A.min(axis=0) # 每一列的最小值

array([336.02543656, 327.71107039, 292.81313347, 341.78208813,
       324.56682092])

这个函数返回四个值，对应着四列。  

类似的，我们也可以计算每一行的最大值：

In [8]:
rt_A.max(axis=1)

array([398.01922181, 373.63206921, 392.61146487, 388.43002901,
       422.02454323, 364.45101093, 397.24041208, 379.39700871,
       378.11608627, 379.87091476])

### 其他聚合函数  

| 函数名称      |   NaN安全版本  | 说明                                   |  
|-------------------|---------------------|-----------------------------------------------|  
| ``np.sum``        | ``np.nansum``       | 计算总和                       |  
| ``np.prod``       | ``np.nanprod``      | 计算乘积                   |  
| ``np.mean``       | ``np.nanmean``      | 计算平均值                      |  
| ``np.std``        | ``np.nanstd``       | 计算标准差                    |  
| ``np.var``        | ``np.nanvar``       | 计算方差                              |  
| ``np.min``        | ``np.nanmin``       | 计算最小值                            |  
| ``np.max``        | ``np.nanmax``       | 计算最大值                            |  
| ``np.argmin``     | ``np.nanargmin``    | 寻找最小值的序号                   |  
| ``np.argmax``     | ``np.nanargmax``    | 寻找最大值的序号                   |  
| ``np.median``     | ``np.nanmedian``    | 计算中位值                    |  
| ``np.percentile`` | ``np.nanpercentile``| 计算百分比分布的对应值     |  
| ``np.any``        | N/A                 | 是否含有True值        |  
| ``np.all``        | N/A                 | 是否全为True值        |  



> 🔔本节的内容到这里就结束了，请前往下一节：4. pandas 数据提取